name: Lint
on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - name: Install client deps
        run: npm ci
        working-directory: client
      - name: Install api deps
        run: npm ci
        working-directory: api
      - run: npm run eslint
